# Running the Docker job only if the Dockerfile was changed.
trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - Dockerfile
    
jobs:
- job: DockerBuild
  pool:
    vmImage: ubuntu-18.04
  # TODO: Add caching.
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: false

  - task: Docker@2
    inputs:
      command: build
      Dockerfile: Dockerfile
      tags: |
        ort
